services:
  django:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 backend_django.asgi:application
    env_file:
      - ./backend_django/.env
    volumes:
      - .:/app
      - ./backend_django/serviceAccountKey.json:/app/backend_django/serviceAccountKey.json
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A backend_django worker --loglevel=info
    env_file:
      - ./backend_django/.env
    volumes:
      - .:/app
      - ./backend_django/serviceAccountKey.json:/app/backend_django/serviceAccountKey.json
    depends_on:
      - django
      - redis

  celery-beat:
    build: .
    command: celery -A backend_django beat --loglevel=info
    env_file:
      - ./backend_django/.env
    volumes:
      - .:/app
      - ./backend_django/serviceAccountKey.json:/app/backend_django/serviceAccountKey.json
    depends_on:
      - django
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  
  # ngrok:
  #   image: ngrok/ngrok:latest
  #   restart: unless-stopped
  #   ports:
  #     - "4040:4040" 
  #   env_file:
  #     - ./backend_django/.env
  #   command: http --url=rational-ready-marmoset.ngrok-free.app django:8000
  #   depends_on:
  #     - django 

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    depends_on:
      - django
