services:
  django:
    build: .
    volumes:
      - .:/app
      - ./backend_django/serviceAccountKey.json:/app/serviceAccountKey.json
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A backend_django worker --loglevel=info
    volumes:
      - .:/app
      - ./backend_django/serviceAccountKey.json:/app/serviceAccountKey.json
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A backend_django beat --loglevel=info
    volumes:
      - .:/app
      - ./backend_django/serviceAccountKey.json:/app/serviceAccountKey.json
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
